### PR TITLE
Mark imported users as such when importing

### LINKED ISSUE #43: Add a new member signup method option for "Imported"
Corresponds to https://github.com/restrictcontentpro/restrict-content-pro/issues/1755

### PR DESCRIPTION
**Pull request by tnorthcutt**
Provides a filter for overriding.

Closes #43 
Also part of https://github.com/restrictcontentpro/restrict-content-pro/issues/1755

### CODE REVIEW

**Comment by tnorthcutt** [comment]
Should be merged _after_ https://github.com/restrictcontentpro/restrict-content-pro/pull/1761

One note: if a site admin updates this plugin before updating RCP and imports users, the edit member screen for those imported users will be somewhat broken, since their signup method will be `imported` before that's supported in RCP. Not sure how to best handled this.

Do we need to perform an RCP version check here before setting this status?

**Comment by nosegraze** [comment]
Yes you can check the `RCP_PLUGIN_VERSION` constant.

**Comment by mindctrl** [comment]
I'd prefer we not introduce a filter, which is just an API we have to maintain. We've had some chats about merging CSV imports into core.

Also, unless there's a filter on the other end, the dropdown will break and default to "manual". I'd rather we leave it hardcoded to "imported".

**Comment by tnorthcutt** [comment]
@mindctrl makes sense! Removed.

**Comment by tnorthcutt** [comment]
@mindctrl heads up, we don't have an RCP version check in here. Do we still need to add that?

**Comment by mindctrl** [comment]
Ah yes, I suppose we should. Can you open a new PR for that, referencing the same issue?

**Comment by tnorthcutt** [comment]
@mindctrl done 👍

**Pull request merged**
